# SwiftLint Configuration for TextEnhancer
# See https://github.com/realm/SwiftLint for documentation

# Directories to include/exclude
included:
  - TextEnhancer/
  - Tests/

excluded:
  - .build/
  - Package.resolved
  - .git/
  - .github/

# Disabled rules - being more lenient for now
disabled_rules:
  - trailing_whitespace # Let SwiftFormat handle this
  - vertical_whitespace # Let SwiftFormat handle this
  - force_unwrapping # Common in test code
  - force_try # Common in test code
  - force_cast # Sometimes necessary for API responses
  - line_length # Can be strict, we'll use warnings instead
  - function_body_length # Can be strict for complex functions
  - type_body_length # Can be strict for managers
  - identifier_name # API parameters use snake_case by design
  - trailing_newline # Let SwiftFormat handle this
  - implicit_return # Not always desired
  - attributes # Formatting preference
  - cyclomatic_complexity # Some complex functions are acceptable
  - redundant_string_enum_value # Sometimes clarity is preferred
  - sorted_imports # Not critical for functionality
  - number_separator # Not critical for functionality
  - pattern_matching_keywords # Style preference
  - opening_brace # Let SwiftFormat handle this
  - trailing_comma # Style preference
  - redundant_optional_initialization # Sometimes explicit is better
  - multiple_closures_with_trailing_closure # SwiftUI style
  - inclusive_language # False positives on technical terms
  - redundant_discardable_let # Style preference
  - for_where # Sometimes explicit if is clearer
  - non_optional_string_data_conversion # Test code compatibility

# Focus on critical opt-in rules only
opt_in_rules:
  - empty_collection_literal
  - empty_count
  - empty_string
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - first_where
  - last_where
  - legacy_random
  - reduce_into
  - redundant_nil_coalescing
  - toggle_bool
  - unavailable_function

# Lenient rule configurations - only for enabled rules

function_parameter_count:
  warning: 8
  error: 10

# type_body_length is disabled

file_length:
  warning: 800
  error: 1500
  ignore_comment_only_lines: true

# cyclomatic_complexity is disabled

nesting:
  type_level:
    warning: 5
    error: 8
  function_level:
    warning: 5
    error: 8

# identifier_name is disabled

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 70

# Very lenient custom rules - focus on critical issues only
custom_rules:
  # Only prevent obvious security issues
  no_hardcoded_secrets:
    name: "No hardcoded secrets"
    regex: '(password|secret|token|key)\s*=\s*"[^"]{10,}"'
    message: "Avoid hardcoded secrets"
    severity: error

# Very lenient severity levels
warning_threshold: 50   # Allow many warnings
# Removed error_threshold as it's not a valid key 