# SwiftLint Configuration for TextEnhancer
# See https://github.com/realm/SwiftLint for documentation

# Directories to include/exclude
included:
  - Sources/
  - Tests/

excluded:
  - .build/
  - Package.resolved
  - .git/
  - .github/

# Disabled rules - being more lenient for now
disabled_rules:
  - trailing_whitespace # Let SwiftFormat handle this
  - vertical_whitespace # Let SwiftFormat handle this
  - force_unwrapping # Common in test code
  - force_try # Common in test code
  - force_cast # Sometimes necessary for API responses
  - line_length # Can be strict, we'll use warnings instead
  - function_body_length # Can be strict for complex functions
  - type_body_length # Can be strict for managers
  - identifier_name # API parameters use snake_case by design
  - trailing_newline # Let SwiftFormat handle this
  - implicit_return # Not always desired
  - attributes # Formatting preference
  - cyclomatic_complexity # Some complex functions are acceptable
  - redundant_string_enum_value # Sometimes clarity is preferred
  - sorted_imports # Not critical for functionality
  - number_separator # Not critical for functionality
  - pattern_matching_keywords # Style preference

# Focus on critical opt-in rules only
opt_in_rules:
  - empty_collection_literal
  - empty_count
  - empty_string
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - first_where
  - last_where
  - legacy_random
  - reduce_into
  - redundant_nil_coalescing
  - toggle_bool
  - unavailable_function

# Lenient rule configurations
line_length:
  warning: 150  # More lenient
  error: 200    # Very lenient
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100  # More lenient
  error: 150    # Very lenient

function_parameter_count:
  warning: 8
  error: 10

type_body_length:
  warning: 500  # More lenient
  error: 800    # Very lenient

file_length:
  warning: 800
  error: 1500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15  # More lenient
  error: 25    # Very lenient

nesting:
  type_level:
    warning: 5
    error: 8
  function_level:
    warning: 5
    error: 8

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50  # More lenient
    error: 70    # Very lenient
  excluded:
    - id
    - url
    - key
    - api
    - app
    - ui
    - os
    - max_tokens    # API parameter
    - image_url     # API parameter
    - finish_reason # API parameter
    - prompt_tokens # API parameter
    - completion_tokens # API parameter
    - total_tokens  # API parameter
    - media_type    # API parameter
    - stop_reason   # API parameter
    - stop_sequence # API parameter
    - input_tokens  # API parameter
    - output_tokens # API parameter

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 70

# Very lenient custom rules - focus on critical issues only
custom_rules:
  # Only prevent obvious security issues
  no_hardcoded_secrets:
    name: "No hardcoded secrets"
    regex: '(password|secret|token|key)\s*=\s*"[^"]{10,}"'
    message: "Avoid hardcoded secrets"
    severity: error

# Very lenient severity levels
warning_threshold: 50   # Allow many warnings
error_threshold: 20     # Allow some errors 